### ISSUE TITLE
Subscript characters are all overlaid on top of each other

### ISSUE THREAD

**Issue by chriscarrollsmith** [owickstrom/the-monospace-web#22]
Here's the fix:

```css
sub {
  font-size: 0.75rem;
  vertical-align: sub;
  line-height: 1;
}
```
